[package]
name = "cross-corr-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.0"
egui = "0.31.0"
egui_plot = "0.31.0"
env_logger = "0.11.6"
num = "0.4.3"
num-complex = "0.4.6"
rustfft = "6.2.0"
